from typing import Literal
# Note lists below were generated by Google Gemini
# 2020
batters_2020 = {
    "Baltimore Orioles": ["Renato Núñez", "Rio Ruiz", "José Iglesias"],
    "Boston Red Sox": ["Rafael Devers", "Xander Bogaerts", "Alex Verdugo"],
    "New York Yankees": ["DJ LeMahieu", "Luke Voit", "Aaron Judge"],
    "Tampa Bay Rays": ["Brandon Lowe", "Joey Wendle"],
    "Toronto Blue Jays": ["Teoscar Hernández", "Lourdes Gurriel Jr.", "Cavan Biggio"],

    "Chicago White Sox": ["José Abreu", "Tim Anderson", "Eloy Jiménez"],
    "Cleveland Guardians": ["José Ramírez", "Cesar Hernandez", "Franmil Reyes"],
    "Detroit Tigers": ["Jeimer Candelario", "Jonathan Schoop"],
    "Kansas City Royals": ["Salvador Perez", "Whit Merrifield"],
    "Minnesota Twins": ["Nelson Cruz", "Josh Donaldson", "Max Kepler"],

    "Houston Astros": ["George Springer", "Jose Altuve", "Michael Brantley"],
    "Los Angeles Angels": ["Mike Trout", "Anthony Rendon", "David Fletcher"],
    "Oakland Athletics": ["Matt Olson", "Mark Canha", "Ramón Laureano"],
    "Seattle Mariners": ["Kyle Lewis", "Kyle Seager"],
    "Texas Rangers": ["Joey Gallo", "Isiah Kiner-Falefa"],

    "Atlanta Braves": ["Freddie Freeman", "Marcell Ozuna", "Ronald Acuña Jr."],
    "Miami Marlins": ["Brian Anderson", "Garrett Cooper"],
    "New York Mets": ["Michael Conforto", "Dominic Smith", "Brandon Nimmo"],
    "Philadelphia Phillies": ["Bryce Harper", "J.T. Realmuto", "Didi Gregorius"],
    "Washington Nationals": ["Juan Soto", "Trea Turner", "Josh Bell"],

    "Chicago Cubs": ["Ian Happ", "Willson Contreras", "Anthony Rizzo"],
    "Cincinnati Reds": ["Nick Castellanos", "Jesse Winker", "Mike Moustakas"],
    "Milwaukee Brewers": ["Christian Yelich", "Jed Lowrie"], # Limited impactful bats in 2020
    "Pittsburgh Pirates": ["Bryan Reynolds", "Colin Moran"],
    "St. Louis Cardinals": ["Paul Goldschmidt", "Brad Miller", "Yadier Molina"],

    "Arizona Diamondbacks": ["Ketel Marte", "Eduardo Escobar", "Christian Walker"],
    "Colorado Rockies": ["Trevor Story", "Charlie Blackmon", "C.J. Cron"],
    "Los Angeles Dodgers": ["Mookie Betts", "Corey Seager", "Justin Turner"],
    "San Diego Padres": ["Fernando Tatis Jr.", "Manny Machado", "Wil Myers"],
    "San Francisco Giants": ["Mike Yastrzemski", "Brandon Belt", "Donovan Solano"]
}

pitchers_2020 = {
    "Baltimore Orioles": ["John Means", "Tanner Scott"],
    "Boston Red Sox": ["Nathan Eovaldi", "Martin Perez"],
    "New York Yankees": ["Gerrit Cole", "Chad Green", "Zack Britton"],
    "Tampa Bay Rays": ["Tyler Glasnow", "Blake Snell", "Nick Anderson"],
    "Toronto Blue Jays": ["Hyun Jin Ryu", "Taijuan Walker", "Anthony Bass"],

    "Chicago White Sox": ["Lucas Giolito", "Dallas Keuchel", "Liam Hendriks"],
    "Cleveland Guardians": ["Shane Bieber", "Carlos Carrasco", "James Karinchak"],
    "Detroit Tigers": ["Spencer Turnbull", "Matthew Boyd"],
    "Kansas City Royals": ["Brad Keller", "Danny Duffy", "Greg Holland"],
    "Minnesota Twins": ["Kenta Maeda", "Tyler Duffey", "Taylor Rogers"],

    "Houston Astros": ["Zack Greinke", "Framber Valdez", "Lance McCullers Jr."],
    "Los Angeles Angels": ["Dylan Bundy", "Griffin Canning", "Raisel Iglesias"], # Iglesias was acquired mid-season
    "Oakland Athletics": ["Chris Bassitt", "Jesús Luzardo", "Liam Hendriks"], # Hendriks was traded mid-season
    "Seattle Mariners": ["Marco Gonzales", "Justus Sheffield"],
    "Texas Rangers": ["Lance Lynn", "Kyle Cody"],

    "Atlanta Braves": ["Max Fried", "Ian Anderson", "Darrell Ceciliani"], # Ceciliani had very limited appearances, but was on the roster.
    "Miami Marlins": ["Sandy Alcántara", "Pablo López", "Sixto Sánchez"],
    "New York Mets": ["Jacob deGrom", "Seth Lugo", "Edwin Díaz"],
    "Philadelphia Phillies": ["Zack Wheeler", "Aaron Nola"],
    "Washington Nationals": ["Max Scherzer", "Patrick Corbin", "Daniel Hudson"],

    "Chicago Cubs": ["Yu Darvish", "Kyle Hendricks", "Craig Kimbrel"],
    "Cincinnati Reds": ["Trevor Bauer", "Sonny Gray", "Raisel Iglesias"],
    "Milwaukee Brewers": ["Corbin Burnes", "Brandon Woodruff", "Devin Williams"],
    "Pittsburgh Pirates": ["Joe Musgrove", "Richard Rodriguez"],
    "St. Louis Cardinals": ["Kwang Hyun Kim", "Jack Flaherty", "Giovanny Gallegos"],

    "Arizona Diamondbacks": ["Zac Gallen", "Luke Weaver", "Stefan Crichton"],
    "Colorado Rockies": ["Germán Márquez", "Antonio Senzatela", "Daniel Bard"],
    "Los Angeles Dodgers": ["Clayton Kershaw", "Walker Buehler", "Dustin May"],
    "San Diego Padres": ["Dinelson Lamet", "Zach Davies", "Drew Pomeranz"],
    "San Francisco Giants": ["Kevin Gausman", "Johnny Cueto", "Sammy Long"] # Long had very limited appearances, but was on the roster
}
# 2021
batters_2021 = {
    "Baltimore Orioles": ["Cedric Mullins", "Ryan Mountcastle"],
    "Boston Red Sox": ["Rafael Devers", "Xander Bogaerts"],
    "New York Yankees": ["Aaron Judge", "Giancarlo Stanton"],
    "Tampa Bay Rays": ["Brandon Lowe"],
    "Toronto Blue Jays": ["Vladimir Guerrero Jr.", "Marcus Semien"],

    "Chicago White Sox": ["José Abreu", "Tim Anderson"],
    "Cleveland Guardians": ["José Ramírez"],
    "Detroit Tigers": ["Robbie Grossman", "Jeimer Candelario"],
    "Kansas City Royals": ["Salvador Perez", "Whit Merrifield"],
    "Minnesota Twins": ["Byron Buxton", "Josh Donaldson", "Jorge Polanco"],

    "Houston Astros": ["Carlos Correa", "Jose Altuve", "Yordan Alvarez"],
    "Los Angeles Angels": ["Shohei Ohtani", "Mike Trout", "Jared Walsh"], # Ohtani is both, listed here for his bat impact
    "Oakland Athletics": ["Matt Olson"],
    "Seattle Mariners": ["Ty France", "Mitch Haniger"],
    "Texas Rangers": ["Adolis García", "Joey Gallo"],

    "Atlanta Braves": ["Freddie Freeman", "Ronald Acuña Jr.", "Austin Riley"],
    "Miami Marlins": ["Jazz Chisholm Jr."],
    "New York Mets": ["Pete Alonso", "Francisco Lindor"],
    "Philadelphia Phillies": ["Bryce Harper", "J.T. Realmuto"],
    "Washington Nationals": ["Juan Soto", "Josh Bell"],

    "Chicago Cubs": ["Willson Contreras", "Javier Báez"], # Javier Báez (before trade)
    "Cincinnati Reds": ["Joey Votto", "Nick Castellanos", "Jesse Winker"],
    "Milwaukee Brewers": [], # Top players were primarily pitchers
    "Pittsburgh Pirates": ["Bryan Reynolds", "Ke'Bryan Hayes", "Adam Frazier"], # Adam Frazier (before trade)
    "St. Louis Cardinals": ["Paul Goldschmidt", "Nolan Arenado"],

    "Arizona Diamondbacks": ["Ketel Marte", "Eduardo Escobar", "David Peralta"], # Eduardo Escobar (before trade)
    "Colorado Rockies": ["C.J. Cron", "Trevor Story"],
    "Los Angeles Dodgers": ["Mookie Betts", "Trea Turner"], # Trea Turner (after trade)
    "San Diego Padres": ["Fernando Tatis Jr.", "Manny Machado"],
    "San Francisco Giants": ["Buster Posey", "Brandon Crawford"]
}

pitchers_2021 = {
    "Baltimore Orioles": ["John Means"],
    "Boston Red Sox": ["Nathan Eovaldi"],
    "New York Yankees": ["Gerrit Cole"],
    "Tampa Bay Rays": ["Shane McClanahan", "Drew Rasmussen", "Tyler Glasnow"], # Glasnow was impactful when healthy
    "Toronto Blue Jays": ["Robbie Ray"],

    "Chicago White Sox": ["Lance Lynn", "Carlos Rodón", "Liam Hendriks"],
    "Cleveland Guardians": ["Shane Bieber", "Emmanuel Clase", "Cal Quantrill"],
    "Detroit Tigers": ["Casey Mize", "Tarik Skubal", "Gregory Soto"],
    "Kansas City Royals": [],
    "Minnesota Twins": [],

    "Houston Astros": ["Lance McCullers Jr.", "Luis Garcia", "Zack Greinke"],
    "Los Angeles Angels": ["Shohei Ohtani", "Raisel Iglesias"], # Ohtani is both, listed here for his pitching impact
    "Oakland Athletics": ["Sean Manaea", "Chris Bassitt", "Frankie Montas"],
    "Seattle Mariners": ["Yusei Kikuchi", "Logan Gilbert", "Paul Sewald"],
    "Texas Rangers": ["Kyle Gibson"],

    "Atlanta Braves": ["Max Fried", "Charlie Morton", "Ian Anderson"],
    "Miami Marlins": ["Sandy Alcántara", "Trevor Rogers"],
    "New York Mets": ["Jacob deGrom", "Taijuan Walker", "Edwin Díaz"],
    "Philadelphia Phillies": ["Zack Wheeler", "Aaron Nola"],
    "Washington Nationals": ["Max Scherzer"], # Max Scherzer (before trade)

    "Chicago Cubs": ["Kyle Hendricks"],
    "Cincinnati Reds": ["Wade Miley", "Luis Castillo", "Tyler Mahle"],
    "Milwaukee Brewers": ["Corbin Burnes", "Brandon Woodruff", "Josh Hader"],
    "Pittsburgh Pirates": [],
    "St. Louis Cardinals": ["Adam Wainwright", "Alex Reyes", "Jack Flaherty"],

    "Arizona Diamondbacks": ["Merrill Kelly", "Zac Gallen"],
    "Colorado Rockies": ["Germán Márquez"],
    "Los Angeles Dodgers": ["Walker Buehler", "Julio Urías", "Max Scherzer"], # Max Scherzer (after trade)
    "San Diego Padres": ["Joe Musgrove", "Blake Snell", "Mark Melancon"],
    "San Francisco Giants": ["Kevin Gausman", "Logan Webb", "Anthony DeSclafani"]
}

# 2022
# Corrected for 2022 season (approximately 3 players total per team)
batters_2022 = {
    "Baltimore Orioles": ["Adley Rutschman", "Anthony Santander", "Cedric Mullins"],
    "Boston Red Sox": ["Rafael Devers", "Xander Bogaerts"],
    "New York Yankees": ["Aaron Judge", "Anthony Rizzo"],
    "Tampa Bay Rays": ["Yandy Díaz", "Randy Arozarena"],
    "Toronto Blue Jays": ["Vladimir Guerrero Jr.", "Alejandro Kirk", "Bo Bichette"],

    "Chicago White Sox": ["José Abreu", "Andrew Vaughn", "Luis Robert Jr."],
    "Cleveland Guardians": ["José Ramírez", "Steven Kwan", "Andrés Giménez"],
    "Detroit Tigers": ["Javier Báez", "Miguel Cabrera"],
    "Kansas City Royals": ["Salvador Perez", "Bobby Witt Jr."],
    "Minnesota Twins": ["Luis Arraez", "Carlos Correa", "Byron Buxton"],

    "Houston Astros": ["Yordan Alvarez", "Jose Altuve", "Kyle Tucker"],
    "Los Angeles Angels": ["Shohei Ohtani", "Mike Trout", "Taylor Ward"], # Ohtani listed here for his bat
    "Oakland Athletics": ["Sean Murphy", "Seth Brown"],
    "Seattle Mariners": ["Julio Rodríguez", "Ty France", "Eugenio Suárez"],
    "Texas Rangers": ["Corey Seager", "Nathaniel Lowe", "Marcus Semien"],

    "Atlanta Braves": ["Austin Riley", "Dansby Swanson", "Matt Olson"],
    "Miami Marlins": ["Miguel Rojas", "Garrett Cooper"],
    "New York Mets": ["Pete Alonso", "Jeff McNeil", "Francisco Lindor"],
    "Philadelphia Phillies": ["Bryce Harper", "Kyle Schwarber", "J.T. Realmuto"],
    "Washington Nationals": ["Juan Soto", "Josh Bell"], # Both traded mid-season but were the key bats early

    "Chicago Cubs": ["Ian Happ", "Willson Contreras"],
    "Cincinnati Reds": ["Kyle Farmer", "Jonathan India", "Brandon Drury"],
    "Milwaukee Brewers": ["Rowdy Tellez", "Willy Adames", "Christian Yelich"],
    "Pittsburgh Pirates": ["Bryan Reynolds", "Ke'Bryan Hayes"],
    "St. Louis Cardinals": ["Paul Goldschmidt", "Nolan Arenado", "Tommy Edman"],

    "Arizona Diamondbacks": ["Christian Walker", "Ketel Marte", "Daulton Varsho"],
    "Colorado Rockies": ["C.J. Cron", "Brendan Rodgers", "Ryan McMahon"],
    "Los Angeles Dodgers": ["Freddie Freeman", "Mookie Betts", "Trea Turner"],
    "San Diego Padres": ["Manny Machado", "Jake Cronenworth", "Juan Soto"], # Soto (after trade)
    "San Francisco Giants": ["Mike Yastrzemski", "J.D. Davis"]
}

pitchers_2022 = {
    "Baltimore Orioles": ["Dean Kremer", "Félix Bautista"],
    "Boston Red Sox": ["Nathan Eovaldi", "Michael Wacha", "Garrett Whitlock"],
    "New York Yankees": ["Gerrit Cole", "Nestor Cortes", "Clay Holmes"],
    "Tampa Bay Rays": ["Shane McClanahan", "Drew Rasmussen", "Jeffrey Springs"],
    "Toronto Blue Jays": ["Alek Manoah", "Kevin Gausman", "Jordan Romano"],

    "Chicago White Sox": ["Dylan Cease", "Lance Lynn", "Liam Hendriks"],
    "Cleveland Guardians": ["Shane Bieber", "Triston McKenzie", "Emmanuel Clase"],
    "Detroit Tigers": ["Tarik Skubal", "Gregory Soto"],
    "Kansas City Royals": ["Brady Singer", "Scott Barlow"],
    "Minnesota Twins": ["Joe Ryan", "Sonny Gray", "Jhoan Duran"],

    "Houston Astros": ["Justin Verlander", "Framber Valdez", "Cristian Javier"],
    "Los Angeles Angels": ["Shohei Ohtani", "Patrick Sandoval"], # Ohtani listed here for his arm
    "Oakland Athletics": ["Paul Blackburn", "Cole Irvin", "Domingo Acevedo"],
    "Seattle Mariners": ["Luis Castillo", "Logan Gilbert", "George Kirby"],
    "Texas Rangers": ["Martín Pérez", "Jon Gray", "Brock Burke"],

    "Atlanta Braves": ["Kyle Wright", "Max Fried", "Spencer Strider"],
    "Miami Marlins": ["Sandy Alcántara", "Pablo López", "Trevor Rogers"],
    "New York Mets": ["Max Scherzer", "Jacob deGrom", "Edwin Díaz"],
    "Philadelphia Phillies": ["Zack Wheeler", "Aaron Nola", "Seranthony Domínguez"],
    "Washington Nationals": ["Josiah Gray", "Patrick Corbin"],

    "Chicago Cubs": ["Justin Steele", "Marcus Stroman"],
    "Cincinnati Reds": ["Hunter Greene", "Nick Lodolo", "Alexis Díaz"],
    "Milwaukee Brewers": ["Corbin Burnes", "Brandon Woodruff", "Devin Williams"],
    "Pittsburgh Pirates": ["Mitch Keller", "David Bednar"],
    "St. Louis Cardinals": ["Miles Mikolas", "Adam Wainwright", "Ryan Helsley"],

    "Arizona Diamondbacks": ["Zac Gallen", "Merrill Kelly"],
    "Colorado Rockies": ["Germán Márquez", "Kyle Freeland", "Daniel Bard"],
    "Los Angeles Dodgers": ["Julio Urías", "Tony Gonsolin", "Evan Phillips"],
    "San Diego Padres": ["Joe Musgrove", "Yu Darvish", "Josh Hader"],
    "San Francisco Giants": ["Logan Webb", "Carlos Rodón", "Alex Wood"]
}

# 2023
# Corrected for 2023 season (approximately 3 players total per team)
batters_2023 = {
    "Baltimore Orioles": ["Adley Rutschman", "Gunnar Henderson"],
    "Boston Red Sox": ["Rafael Devers", "Masataka Yoshida"],
    "New York Yankees": ["Aaron Judge", "Gleyber Torres"],
    "Tampa Bay Rays": ["Yandy Díaz", "Randy Arozarena"],
    "Toronto Blue Jays": ["Vladimir Guerrero Jr.", "Bo Bichette"],

    "Chicago White Sox": ["Luis Robert Jr.", "Andrew Vaughn"],
    "Cleveland Guardians": ["José Ramírez", "Steven Kwan"],
    "Detroit Tigers": ["Spencer Torkelson", "Riley Greene"],
    "Kansas City Royals": ["Bobby Witt Jr.", "Salvador Perez"],
    "Minnesota Twins": ["Carlos Correa", "Byron Buxton"], # Luis Arraez was traded mid-season but impactful before

    "Houston Astros": ["Yordan Alvarez", "Jose Altuve", "Kyle Tucker"],
    "Los Angeles Angels": ["Shohei Ohtani", "Mike Trout"], # Ohtani for his bat
    "Oakland Athletics": ["Brent Rooker", "Zack Gelof"],
    "Seattle Mariners": ["Julio Rodríguez", "Cal Raleigh"],
    "Texas Rangers": ["Corey Seager", "Marcus Semien", "Adolis García"],

    "Atlanta Braves": ["Ronald Acuña Jr.", "Matt Olson", "Austin Riley"],
    "Miami Marlins": ["Luis Arraez", "Jorge Soler"], # Arraez (after trade)
    "New York Mets": ["Pete Alonso", "Francisco Lindor"],
    "Philadelphia Phillies": ["Kyle Schwarber", "Bryce Harper", "Trea Turner"],
    "Washington Nationals": ["Joey Meneses", "CJ Abrams"],

    "Chicago Cubs": ["Cody Bellinger", "Dansby Swanson"],
    "Cincinnati Reds": ["Spencer Steer", "Elly De La Cruz", "Matt McLain"],
    "Milwaukee Brewers": ["Christian Yelich", "William Contreras"],
    "Pittsburgh Pirates": ["Bryan Reynolds", "Ke'Bryan Hayes"],
    "St. Louis Cardinals": ["Paul Goldschmidt", "Nolan Arenado"],

    "Arizona Diamondbacks": ["Corbin Carroll", "Ketel Marte", "Christian Walker"],
    "Colorado Rockies": ["Elias Díaz", "Ryan McMahon"],
    "Los Angeles Dodgers": ["Freddie Freeman", "Mookie Betts", "Will Smith"],
    "San Diego Padres": ["Juan Soto", "Fernando Tatis Jr.", "Manny Machado"],
    "San Francisco Giants": ["LaMonte Wade Jr.", "Patrick Bailey"]
}

pitchers_2023 = {
    "Baltimore Orioles": ["Kyle Bradish"],
    "Boston Red Sox": ["Brayan Bello", "Kenley Jansen"],
    "New York Yankees": ["Gerrit Cole"],
    "Tampa Bay Rays": ["Shane McClanahan", "Zach Eflin"],
    "Toronto Blue Jays": ["Kevin Gausman", "Jordan Romano"],

    "Chicago White Sox": ["Dylan Cease"],
    "Cleveland Guardians": ["Emmanuel Clase"],
    "Detroit Tigers": ["Eduardo Rodriguez", "Tarik Skubal"],
    "Kansas City Royals": ["Cole Ragans"],
    "Minnesota Twins": ["Pablo López", "Sonny Gray", "Jhoan Duran"],

    "Houston Astros": ["Framber Valdez", "Justin Verlander"],
    "Los Angeles Angels": ["Shohei Ohtani"], # Ohtani for his arm
    "Oakland Athletics": ["JP Sears"],
    "Seattle Mariners": ["Luis Castillo", "George Kirby"],
    "Texas Rangers": ["Nathan Eovaldi", "Jordan Montgomery"],

    "Atlanta Braves": ["Spencer Strider"],
    "Miami Marlins": ["Jesús Luzardo", "Eury Pérez"],
    "New York Mets": ["Kodai Senga"],
    "Philadelphia Phillies": ["Zack Wheeler", "Aaron Nola"],
    "Washington Nationals": ["Josiah Gray"],

    "Chicago Cubs": ["Justin Steele", "Marcus Stroman"],
    "Cincinnati Reds": ["Alexis Díaz"],
    "Milwaukee Brewers": ["Corbin Burnes", "Freddy Peralta", "Devin Williams"],
    "Pittsburgh Pirates": ["Mitch Keller", "David Bednar"],
    "St. Louis Cardinals": ["Ryan Helsley"],

    "Arizona Diamondbacks": ["Zac Gallen", "Merrill Kelly"],
    "Colorado Rockies": ["Kyle Freeland"],
    "Los Angeles Dodgers": ["Clayton Kershaw"],
    "San Diego Padres": ["Blake Snell"],
    "San Francisco Giants": ["Logan Webb", "Alex Cobb"]
}

# 2024
batters_2024 = {
    "Baltimore Orioles": ["Gunnar Henderson", "Adley Rutschman"],
    "Boston Red Sox": ["Rafael Devers", "Triston Casas"],
    "New York Yankees": ["Aaron Judge", "Juan Soto"],
    "Tampa Bay Rays": ["Yandy Díaz", "Isaac Paredes"],
    "Toronto Blue Jays": ["Vladimir Guerrero Jr.", "Bo Bichette"],

    "Chicago White Sox": ["Luis Robert Jr."],
    "Cleveland Guardians": ["José Ramírez", "Steven Kwan"],
    "Detroit Tigers": ["Riley Greene", "Spencer Torkelson"],
    "Kansas City Royals": ["Bobby Witt Jr.", "Salvador Perez"],
    "Minnesota Twins": ["Carlos Correa", "Royce Lewis"],

    "Houston Astros": ["Yordan Alvarez", "Jose Altuve", "Kyle Tucker"],
    "Los Angeles Angels": ["Shohei Ohtani", "Mike Trout"], # Ohtani as batter for 2024
    "Oakland Athletics": ["Brent Rooker", "Zack Gelof"],
    "Seattle Mariners": ["Julio Rodríguez", "Cal Raleigh"],
    "Texas Rangers": ["Corey Seager", "Marcus Semien", "Adolis García"],

    "Atlanta Braves": ["Ronald Acuña Jr.", "Matt Olson", "Austin Riley"],
    "Miami Marlins": ["Luis Arraez", "Bryan De La Cruz"],
    "New York Mets": ["Francisco Lindor", "Pete Alonso"],
    "Philadelphia Phillies": ["Bryce Harper", "Kyle Schwarber", "Alec Bohm"],
    "Washington Nationals": ["CJ Abrams", "Lane Thomas"],

    "Chicago Cubs": ["Cody Bellinger", "Dansby Swanson"],
    "Cincinnati Reds": ["Elly De La Cruz", "Spencer Steer"],
    "Milwaukee Brewers": ["William Contreras", "Christian Yelich"],
    "Pittsburgh Pirates": ["Bryan Reynolds", "Oneil Cruz"],
    "St. Louis Cardinals": ["Paul Goldschmidt", "Nolan Arenado"],

    "Arizona Diamondbacks": ["Corbin Carroll", "Ketel Marte", "Christian Walker"],
    "Colorado Rockies": ["Elias Díaz", "Nolan Jones"],
    "Los Angeles Dodgers": ["Mookie Betts", "Freddie Freeman"],
    "San Diego Padres": ["Juan Soto", "Fernando Tatis Jr.", "Manny Machado"],
    "San Francisco Giants": ["LaMonte Wade Jr.", "Patrick Bailey"]
}

pitchers_2024 = {
    "Baltimore Orioles": ["Corbin Burnes"],
    "Boston Red Sox": ["Garrett Crochet"], # Crochet had a strong year after trade
    "New York Yankees": ["Gerrit Cole"],
    "Tampa Bay Rays": ["Zach Eflin"],
    "Toronto Blue Jays": ["Kevin Gausman"],

    "Chicago White Sox": ["Garrett Crochet", "Erick Fedde"], # Crochet split time
    "Cleveland Guardians": ["Emmanuel Clase"],
    "Detroit Tigers": ["Tarik Skubal"],
    "Kansas City Royals": ["Seth Lugo", "Cole Ragans"],
    "Minnesota Twins": ["Pablo López", "Jhoan Duran"],

    "Houston Astros": ["Framber Valdez"],
    "Los Angeles Angels": [], # Ohtani didn't pitch in 2024
    "Oakland Athletics": ["Mason Miller"],
    "Seattle Mariners": ["Luis Castillo", "Logan Gilbert", "George Kirby"],
    "Texas Rangers": ["Nathan Eovaldi"],

    "Atlanta Braves": ["Spencer Strider", "Chris Sale"],
    "Miami Marlins": ["Jesús Luzardo", "Eury Pérez"],
    "New York Mets": ["Kodai Senga", "Edwin Díaz"],
    "Philadelphia Phillies": ["Zack Wheeler", "Aaron Nola"],
    "Washington Nationals": ["Josiah Gray"],

    "Chicago Cubs": ["Shota Imanaga", "Justin Steele"],
    "Cincinnati Reds": ["Nick Lodolo", "Alexis Díaz"],
    "Milwaukee Brewers": ["Freddy Peralta", "Devin Williams"],
    "Pittsburgh Pirates": ["Paul Skenes", "Mitch Keller"],
    "St. Louis Cardinals": ["Sonny Gray", "Ryan Helsley"],

    "Arizona Diamondbacks": ["Zac Gallen", "Merrill Kelly"],
    "Colorado Rockies": ["Cal Quantrill"],
    "Los Angeles Dodgers": ["Tyler Glasnow", "Yoshinobu Yamamoto"],
    "San Diego Padres": ["Dylan Cease", "Michael King"],
    "San Francisco Giants": ["Logan Webb", "Blake Snell"]
}

batters_2025 = {
    "Baltimore Orioles": ["Gunnar Henderson", "Adley Rutschman", "Ryan O'Hearn"],
    "Boston Red Sox": ["Rafael Devers", "Jarren Duran", "Triston Casas"],
    "New York Yankees": ["Aaron Judge", "Juan Soto"],
    "Tampa Bay Rays": ["Yandy Díaz", "Randy Arozarena", "Isaac Paredes"],
    "Toronto Blue Jays": ["Vladimir Guerrero Jr.", "Bo Bichette"],

    "Chicago White Sox": ["Luis Robert Jr.", "Andrew Vaughn"],
    "Cleveland Guardians": ["José Ramírez", "Steven Kwan", "Andrés Giménez"],
    "Detroit Tigers": ["Riley Greene", "Spencer Torkelson"],
    "Kansas City Royals": ["Bobby Witt Jr.", "Salvador Perez", "Vinnie Pasquantino"],
    "Minnesota Twins": ["Carlos Correa", "Royce Lewis", "Byron Buxton"],

    "Houston Astros": ["Yordan Alvarez", "Jose Altuve", "Kyle Tucker"],
    "Los Angeles Angels": ["Shohei Ohtani", "Mike Trout"], # Ohtani continues to bat well
    "Oakland Athletics": ["Brent Rooker", "Shea Langeliers", "Jacob Wilson"],
    "Seattle Mariners": ["Cal Raleigh", "Julio Rodríguez", "Ty France"],
    "Texas Rangers": ["Corey Seager", "Marcus Semien", "Adolis García"],

    "Atlanta Braves": ["Ronald Acuña Jr.", "Matt Olson", "Austin Riley"],
    "Miami Marlins": ["Luis Arraez", "Bryan De La Cruz"],
    "New York Mets": ["Pete Alonso", "Francisco Lindor", "Brandon Nimmo"],
    "Philadelphia Phillies": ["Bryce Harper", "Kyle Schwarber", "Alec Bohm"],
    "Washington Nationals": ["CJ Abrams", "Lane Thomas", "Joey Meneses"],

    "Chicago Cubs": ["Cody Bellinger", "Dansby Swanson", "Seiya Suzuki"],
    "Cincinnati Reds": ["Elly De La Cruz", "Spencer Steer", "Matt McLain"],
    "Milwaukee Brewers": ["William Contreras", "Christian Yelich", "Willy Adames"],
    "Pittsburgh Pirates": ["Bryan Reynolds", "Oneil Cruz"],
    "St. Louis Cardinals": ["Paul Goldschmidt", "Nolan Arenado", "Willson Contreras"],

    "Arizona Diamondbacks": ["Corbin Carroll", "Ketel Marte", "Christian Walker"],
    "Colorado Rockies": ["Elias Díaz", "Nolan Jones", "Ryan McMahon"],
    "Los Angeles Dodgers": ["Mookie Betts", "Freddie Freeman", "Will Smith"],
    "San Diego Padres": ["Juan Soto", "Fernando Tatis Jr.", "Manny Machado"],
    "San Francisco Giants": ["LaMonte Wade Jr.", "Patrick Bailey", "Matt Chapman"]
}

pitchers_2025 = {
    "Baltimore Orioles": ["Corbin Burnes"],
    "Boston Red Sox": ["Garrett Crochet"],
    "New York Yankees": ["Gerrit Cole", "Luis Gil", "Max Fried"], # Fried moved to Yankees, all pitching well
    "Tampa Bay Rays": ["Zach Eflin", "Shane McClanahan"],
    "Toronto Blue Jays": ["Kevin Gausman", "José Berríos"],

    "Chicago White Sox": ["Garrett Crochet", "Erick Fedde"],
    "Cleveland Guardians": ["Emmanuel Clase"],
    "Detroit Tigers": ["Tarik Skubal", "Jack Flaherty"],
    "Kansas City Royals": ["Cole Ragans", "Seth Lugo"],
    "Minnesota Twins": ["Pablo López", "Jhoan Duran"],

    "Houston Astros": ["Framber Valdez", "Hunter Brown", "Justin Verlander"],
    "Los Angeles Angels": [], # Ohtani is primarily batting impact
    "Oakland Athletics": ["Mason Miller", "Paul Blackburn"],
    "Seattle Mariners": ["Luis Castillo", "George Kirby", "Logan Gilbert"],
    "Texas Rangers": ["Nathan Eovaldi", "José Leclerc"],

    "Atlanta Braves": ["Spencer Strider", "Chris Sale"],
    "Miami Marlins": ["Jesús Luzardo", "Sandy Alcántara", "Eury Pérez"],
    "New York Mets": ["Kodai Senga", "Luis Severino", "Edwin Díaz"],
    "Philadelphia Phillies": ["Zack Wheeler", "Aaron Nola", "Ranger Suárez"],
    "Washington Nationals": ["Josiah Gray", "MacKenzie Gore"],

    "Chicago Cubs": ["Shota Imanaga", "Justin Steele"],
    "Cincinnati Reds": ["Hunter Greene", "Nick Lodolo", "Alexis Díaz"],
    "Milwaukee Brewers": ["Freddy Peralta", "Devin Williams"],
    "Pittsburgh Pirates": ["Paul Skenes", "Mitch Keller", "David Bednar"],
    "St. Louis Cardinals": ["Sonny Gray", "Ryan Helsley"],

    "Arizona Diamondbacks": ["Zac Gallen", "Merrill Kelly"],
    "Colorado Rockies": ["Cal Quantrill", "Austin Gomber"],
    "Los Angeles Dodgers": ["Tyler Glasnow", "Yoshinobu Yamamoto", "Bobby Miller"],
    "San Diego Padres": ["Dylan Cease", "Yu Darvish", "Michael King"],
    "San Francisco Giants": ["Logan Webb", "Jordan Hicks", "Blake Snell"]
}

STAR_BATTERS = {
    "2020": batters_2020,
    "2021": batters_2021,
    "2022": batters_2022, 
    "2023": batters_2023,
    "2024": batters_2024,
    "2025": batters_2025
}

STAR_PITCHERS = {
    "2020": pitchers_2020,
    "2021": pitchers_2021,
    "2022": pitchers_2022, 
    "2023": pitchers_2023,
    "2024": pitchers_2024,
    "2025": pitchers_2025
}

def get_star_players(
        team_name: str, 
        year: int, 
        player_set: Literal["batters", "pitchers"]
        ) -> list[str]:
    year_str = str(year)
    if player_set == "batters":
        STAR_PLAYERS = STAR_BATTERS
    else: 
        STAR_PLAYERS = STAR_PITCHERS
    if year_str not in STAR_BATTERS:
        return []
    return STAR_PLAYERS[year_str].get(team_name, [])

